version: 0.2
phases:
   install:
     runtime-versions:
         nodejs: 12.x
   pre_build:
     commands:
         - npm install
   build:
     commands:
         - echo "Creating frontend code zip"
artifacts:
   files:
         - '**/*'
   discard-paths: no
   base-directory: dist